### PR TITLE
[Laravel] Update mime types to fix the accept attribute of Former::file() field v2

### PR DESCRIPTION
**Pull request by tortuetorche**
Fix RTF (`*.rtf`) and PowerPoint (`*.ppt`) mimes type.
Add PowerPoint (`*.pps`, `*.ppsx`, `*.pptx`) and OpenOffice/LibreOffice (`*.odp`, `*.ods`, `*.odt`) mimes type.

Otherwise they aren't listed in the input file dialog:
fix_former_mime_type - copie

### CODE REVIEW

**Comment by tortuetorche** [comment]
Similar to #388

**Comment by tortuetorche** [comment]
The pull request #449 should be merged before this one to get a green build.

**Comment by claar** [comment]
Merged, thanks!

@tortuetorche Would you be interested in co-maintaining this project so you can commit fixes like this yourself?

**Comment by tortuetorche** [comment]
Hi @claar,

Why not, but I've already two packages ([authority-controller](https://github.com/efficiently/authority-controller) and [larasset](https://github.com/efficiently/larasset)) that take me some time.
So, I'll not be a very active co-maintainer...

Cheers,
Tortue Torche

**Comment by claar** [comment]
@tortuetorche Thanks -- I'll see if I can get @Anahkiasen to add you.

For anyone else watching, this project is looking for co-maintainers -- please let me know if you're interested.

**Comment by tortuetorche** [comment]
Hi @claar,

Is it possible to merge this feature in the `master` branch and tag a new release ?

Have a good day,
Tortue Torche

**Comment by claar** [comment]
@tortuetorche Done in 3.5.4

**Comment by tortuetorche** [comment]
Many thanks!

**Pull request merged**
