### PR TITLE
Change Former::config to Former::setOption

### PR DESCRIPTION
**Pull request by jp7carlos**
The docs mention Former::config. Which browsing the source code i think should be Former::setOption.

https://github.com/Anahkiasen/former/issues/424

### CODE REVIEW

**Comment by claar** [comment]
Merged. Thanks so much!

**Comment by Anahkiasen** [comment]
We'll need to actually edit the wiki too, the gh-pages branch is generated from that, but you can't PR the wiki so

**Comment by claar** [comment]
@Anahkiasen Ah, I didn't realize the gh-pages branch was generated from that. So the workflow should be to edit the wiki, then ask you to re-generate gh-pages?

**Comment by Anahkiasen** [comment]
I think it *should* regenerate automatically but I'm not 100% on that

**Comment by claar** [comment]
I've applied these changes to the Wiki.

**Pull request merged**
